repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-toml
      - id: debug-statements
      - id: double-quote-string-fixer
      - id: name-tests-test
        entry: name-tests-test --pytest-test-first
      - id: requirements-txt-fixer
      - id: detect-private-key
      - id: check-json

  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.11.0.1-1
    hooks:
      - id: shellcheck

  - repo: https://github.com/openstack/bashate
    rev: 2.1.1
    hooks:
      - id: bashate
        name: bashate
        description: This hook runs bashate for linting shell scripts
        entry: bashate
        language: python
        types: [shell]

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.16.8
    hooks:
      - id: ruff-check
        name: ruff check
        description: "Run 'ruff check' for extremely fast Python linting"
        entry: ruff check --force-exclude
        language: python
        types_or: [python, pyi, jupyter]
        args: []
        require_serial: true
        additional_dependencies: []
        minimum_pre_commit_version: "2.9.2"

      - id: ruff-format
        name: ruff format
        description: "Run 'ruff format' for extremely fast Python formatting"
        entry: ruff format --force-exclude
        language: python
        types_or: [python, pyi, jupyter]
        args: []
        require_serial: true
        additional_dependencies: []
        minimum_pre_commit_version: "2.9.2"
