name: Lint and test

on: [push]

permissions:
  contents: read        # For checkout and comparing commits
  pull-requests: write  # For creating/updating PR comments

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version:
          - "3.10"
          - "3.11"
          - "3.12"
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          cache-dependency-glob: "uv.lock"

      - name: "Set up Python"
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}

      - name: Analysing the code with pylint
        run: uv run ruff check

      - name: Installing MBROLA
        run: sudo /bin/bash bin/install.sh

      - name: Testing with Pytest
        run: |
          uv run pytest --junitxml=pytest.xml --cov-report=term-missing:skip-covered --cov=src tests/ | tee pytest-coverage.txt
      
      - name: Coverage comment
        uses: MishaKav/pytest-coverage-comment@v1
        with:
          pytest-coverage-path: ./pytest-coverage.txt
          junitxml-path: ./pytest.xml
          hide-emoji: true
      - name: Dynamic Badges
        uses: schneegans/dynamic-badges-action@v1.7.0
        
        with:
            auth: ${{ secrets.GIST_SECRET }}
            gistID: your-gist-id
            filename: coverage.json
            label: Coverage
            message: ${{ steps.coverage.outputs.coverage }}
            color: ${{ steps.coverage.outputs.color }}
        
      - name: Fail if coverage too low
        if: ${{ steps.coverage.outputs.coverage < 80 }}
        run: |
          echo "Coverage is below 80%!"
          exit 1
